// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZbbwD-hCbsNGrVBZVE2YC4VU-Hv1Uc4',
    appId: '1:59289691108:web:8f4449b21cbfa7ed251df1',
    messagingSenderId: '59289691108',
    projectId: 'virtualocation-30cea',
    authDomain: 'virtualocation-30cea.firebaseapp.com',
    databaseURL: 'https://virtualocation-30cea-default-rtdb.firebaseio.com',
    storageBucket: 'virtualocation-30cea.appspot.com',
    measurementId: 'G-4S9P3EMDE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkmhT92McsAHM9YDlrn9bKFkNAlUodOeg',
    appId: '1:59289691108:android:5227117e2beda145251df1',
    messagingSenderId: '59289691108',
    projectId: 'virtualocation-30cea',
    databaseURL: 'https://virtualocation-30cea-default-rtdb.firebaseio.com',
    storageBucket: 'virtualocation-30cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzb9LHp2bz_7Rs47kAj6wRws8gd7OGcfI',
    appId: '1:59289691108:ios:4dd0c160c40a8480251df1',
    messagingSenderId: '59289691108',
    projectId: 'virtualocation-30cea',
    databaseURL: 'https://virtualocation-30cea-default-rtdb.firebaseio.com',
    storageBucket: 'virtualocation-30cea.appspot.com',
    iosBundleId: 'com.example.vloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzb9LHp2bz_7Rs47kAj6wRws8gd7OGcfI',
    appId: '1:59289691108:ios:a8d5ff8559d37624251df1',
    messagingSenderId: '59289691108',
    projectId: 'virtualocation-30cea',
    databaseURL: 'https://virtualocation-30cea-default-rtdb.firebaseio.com',
    storageBucket: 'virtualocation-30cea.appspot.com',
    iosBundleId: 'com.example.vloc.RunnerTests',
  );
}
